apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 992382830933.dkr.ecr.us-east-1.amazonaws.com/springboot-eks-demo:latest
          ports:
            - containerPort: 8093
          readinessProbe:
            httpGet:
              path: /
              port: 8093
            initialDelaySeconds: 10

